ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'START';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'EXPERT';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'SUPPORT';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'MARKETING_PARTNER';
ALTER TYPE "SubscriptionPlan" ADD VALUE IF NOT EXISTS 'IMPLEMENTATION';
